name: 'Type Check'
description: 'Detects the language of comments in your code and checks types.'
author: 'cubxxw'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install typecheck
      run: go install github.com/kubecub/typecheck@latest
      shell: bash

    - name: Run typecheck Detector
      run: typecheck
      shell: bash

branding:
  icon: 'check-square'
  color: 'blue'


# homepage: 'http://github.com/kubecub'
# repository: 'http://github.com/kubecub/typecheck'
