# Copyright © 2024 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: 'Go Code Typecheck'
description: 'Typecheck is a robust cross-platform tool for Go code type checking, leveraging built-in parsing and type-check libraries (go/parser and go/types) for efficient analysis.'
inputs:
  go-version:
    description: 'The version of Go to use for running the detector.'
    required: true
    default: '1.21'
  detector-version:
    description: 'The version of the Comment Language Detector to install.'
    required: false
    default: 'latest'
  config-path:
    description: 'Path to the configuration file for the detector.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install Comment Language Detector
      run: go install github.com/kubecub/typecheck@${{ inputs.detector-version }}
      shell: bash

    - name: Run typecheck
      run: typecheck
      shell: bash

branding:
  icon: 'search'
  color: 'blue'
